/**
 * Thin wrapper — cosmetics map is generated by scripts/split_kconsume_cosmetics.mjs
 */
import { spawnSync } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)));
const r = spawnSync(process.execPath, [join(root, 'scripts', 'split_kconsume_cosmetics.mjs')], {
  cwd: root,
  stdio: 'inherit',
});
process.exit(r.status ?? 1);
