/** Shared sector labels/paths for hub, cross-sector badges, and hub_index. */
export const SECTOR_META = {
  semi: { ko: '반도체', en: 'Semi', shortKo: '반도체', shortEn: 'Semi', icon: '\uD83D\uDCA0', map: 'semiconductor/korea_semiconductor_map.html' },
  bio: { ko: '바이오', en: 'Bio', shortKo: '바이오', shortEn: 'Bio', icon: '\uD83E\uDDEC', map: 'bio/korea_bio_map.html' },
  ship: { ko: '조선', en: 'Ship', shortKo: '조선', shortEn: 'Ship', icon: '\u2693', map: 'ship/korea_ship_map.html' },
  defense: { ko: '방산', en: 'Defense', shortKo: '방산', shortEn: 'Defense', icon: '\uD83D\uDEF0\uFE0F', map: 'defense/korea_defense_map.html' },
  robot: { ko: '로봇', en: 'Robot', shortKo: '로봇', shortEn: 'Robot', icon: '\uD83E\uDD16', map: 'robot/korea_robot_map.html' },
  auto: { ko: '자동차', en: 'Auto', shortKo: '자동차', shortEn: 'Auto', icon: '\uD83D\uDE97', map: 'auto/korea_auto_map.html' },
  medtech: { ko: '의료기기/헬스케어', en: 'MedTech', shortKo: '헬스케어', shortEn: 'MedTech', icon: '\uD83E\uDE7A', map: 'medtech/korea_medtech_map.html' },
  kconsume: { ko: 'K-소비/유통', en: 'K-Consume', shortKo: 'K-소비', shortEn: 'K-Consume', icon: '\uD83D\uDED2', map: 'kconsume/korea_kconsume_map.html' },
  cosmetics: { ko: '화장품/미용기기', en: 'Cosmetics', shortKo: '화장품', shortEn: 'Cosmetics', icon: '\uD83D\uDC84', map: 'cosmetics/korea_cosmetics_map.html' },
  kcontent: { ko: 'K-콘텐츠', en: 'K-Content', shortKo: 'K-콘텐츠', shortEn: 'K-Content', icon: '\uD83C\uDFAC', map: 'kcontent/korea_kcontent_map.html' },
  battery: { ko: '2차전지', en: 'Battery', shortKo: '2차전지', shortEn: 'Battery', icon: '\uD83D\uDD0B', map: 'battery/korea_battery_map.html' },
  renewable: { ko: '신재생', en: 'Renewable', shortKo: '신재생', shortEn: 'Renewable', icon: '\uD83C\uDF31', map: 'renewable/korea_renewable_map.html' },
  nuclear: { ko: '원전', en: 'Nuclear', shortKo: '원전', shortEn: 'Nuclear', icon: '\u269B', map: 'nuclear/korea_nuclear_map.html' },
  powergrid: { ko: '전력설비', en: 'Power Equip.', shortKo: '전력설비', shortEn: 'Power', icon: '\uD83D\uDD0C', map: 'powergrid/korea_powergrid_map.html' },
  finance: { ko: '금융', en: 'Finance', shortKo: '금융', shortEn: 'Finance', icon: '\uD83C\uDFE6', map: 'finance/korea_finance_map.html' },
  construction: { ko: '건설', en: 'Construction', shortKo: '건설', shortEn: 'Construction', icon: '\uD83C\uDFD7\uFE0F', map: 'construction/korea_construction_map.html' },
};

export const HUB_MAP_PATHS = [
  ['semi', 'semiconductor/korea_semiconductor_map.html'],
  ['bio', 'bio/korea_bio_map.inline.js'],
  ['ship', 'ship/korea_ship_map.html'],
  ['defense', 'defense/korea_defense_map.html'],
  ['robot', 'robot/korea_robot_map.html'],
  ['auto', 'auto/korea_auto_map.html'],
  ['medtech', 'medtech/korea_medtech_map.html'],
  ['kconsume', 'kconsume/korea_kconsume_map.html'],
  ['cosmetics', 'cosmetics/korea_cosmetics_map.html'],
  ['kcontent', 'kcontent/korea_kcontent_map.html'],
  ['battery', 'battery/korea_battery_map.html'],
  ['renewable', 'renewable/korea_renewable_map.html'],
  ['nuclear', 'nuclear/korea_nuclear_map.html'],
  ['powergrid', 'powergrid/korea_powergrid_map.html'],
  ['finance', 'finance/korea_finance_map.html'],
  ['construction', 'construction/korea_construction_map.html'],
];
