/** Shared sector labels/paths for hub, cross-sector badges, and hub_index. */
export const SECTOR_META = {
  bigchip: { ko: '삼성전자/하이닉스', en: 'Samsung/SK hynix', shortKo: '삼성/하이닉스', shortEn: 'Samsung/SK hynix', icon: '\uD83C\uDFC6', map: 'bigchip/korea_bigchip_map.html' },
  semi: { ko: '반도체', en: 'Semi', shortKo: '반도체', shortEn: 'Semi', icon: '\uD83D\uDCA0', map: 'semiconductor/korea_semiconductor_map.html' },
  bio: { ko: '바이오', en: 'Bio', shortKo: '바이오', shortEn: 'Bio', icon: '\uD83E\uDDEC', map: 'bio/korea_bio_map.html' },
  ship: { ko: '조선/해운', en: 'Shipbuilding/Shipping', shortKo: '조선/해운', shortEn: 'Shipbuilding/Shipping', icon: '\u2693', map: 'ship/korea_ship_map.html' },
  defense: { ko: '방산/우주', en: 'Defense & Space', shortKo: '방산/우주', shortEn: 'Defense & Space', icon: '\uD83D\uDEF0\uFE0F', map: 'defense/korea_defense_map.html' },
  robot: { ko: '로봇', en: 'Robot', shortKo: '로봇', shortEn: 'Robot', icon: '\uD83E\uDD16', map: 'robot/korea_robot_map.html' },
  auto: { ko: '자동차', en: 'Auto', shortKo: '자동차', shortEn: 'Auto', icon: '\uD83D\uDE97', map: 'auto/korea_auto_map.html' },
  medtech: { ko: '의료기기/헬스케어', en: 'MedTech', shortKo: '헬스케어', shortEn: 'MedTech', icon: '\uD83E\uDE7A', map: 'medtech/korea_medtech_map.html' },
  kconsume: { ko: 'K-소비/유통', en: 'K-Consume', shortKo: 'K-소비', shortEn: 'K-Consume', icon: '\uD83D\uDED2', map: 'kconsume/korea_kconsume_map.html' },
  cosmetics: { ko: '화장품/미용기기', en: 'Cosmetics', shortKo: '화장품', shortEn: 'Cosmetics', icon: '\uD83D\uDC84', map: 'cosmetics/korea_cosmetics_map.html' },
  kcontent: { ko: 'K-콘텐츠', en: 'K-Content', shortKo: 'K-콘텐츠', shortEn: 'K-Content', icon: '\uD83C\uDFAC', map: 'kcontent/korea_kcontent_map.html' },
  battery: { ko: '2차전지', en: 'Battery', shortKo: '2차전지', shortEn: 'Battery', icon: '\uD83D\uDD0B', map: 'battery/korea_battery_map.html' },
  renewable: { ko: '신재생', en: 'Renewable', shortKo: '신재생', shortEn: 'Renewable', icon: '\uD83C\uDF31', map: 'renewable/korea_renewable_map.html' },
  nuclear: { ko: '원전', en: 'Nuclear', shortKo: '원전', shortEn: 'Nuclear', icon: '\u269B', map: 'nuclear/korea_nuclear_map.html' },
  powergrid: { ko: '전력설비', en: 'Power Equip.', shortKo: '전력설비', shortEn: 'Power', icon: '\uD83D\uDD0C', map: 'powergrid/korea_powergrid_map.html' },
  finance: { ko: '금융', en: 'Finance', shortKo: '금융', shortEn: 'Finance', icon: '\uD83C\uDFE6', map: 'finance/korea_finance_map.html' },
  construction: { ko: '건설', en: 'Construction', shortKo: '건설', shortEn: 'Construction', icon: '\uD83C\uDFD7\uFE0F', map: 'construction/korea_construction_map.html' },
  software: { ko: 'IT·소프트웨어', en: 'IT & Software', shortKo: 'IT·SW', shortEn: 'Software', icon: '\uD83D\uDCBB', map: 'software/korea_software_map.html' },
  holdings: { ko: '지주회사', en: 'Holdings', shortKo: '지주회사', shortEn: 'Holdings', icon: '\uD83C\uDFE2', map: 'holdings/korea_holdings_map.html' },
  telecom: { ko: '통신', en: 'Telecom', shortKo: '통신', shortEn: 'Telecom', icon: '\uD83D\uDCE1', map: 'telecom/korea_telecom_map.html' },
  chemical: { ko: '화학·정유', en: 'Chemicals & Refining', shortKo: '화학·정유', shortEn: 'Chemicals', icon: '\u2697\uFE0F', map: 'chemical/korea_chemical_map.html' },
  travel: { ko: '여행·레저·항공', en: 'Travel & Airlines', shortKo: '여행·항공', shortEn: 'Travel', icon: '\u2708\uFE0F', map: 'travel/korea_travel_map.html' },
  elec: { ko: '전기·전자', en: 'Electrical & Electronics', shortKo: '전기·전자', shortEn: 'Electronics', icon: '\uD83D\uDCA1', map: 'elec/korea_elec_map.html' },
  metal: { ko: '철강·금속·기계', en: 'Steel, Metals & Machinery', shortKo: '철강·기계', shortEn: 'Metals', icon: '\u2699\uFE0F', map: 'metal/korea_metal_map.html' },
};

export const HUB_MAP_PATHS = [
  ['bigchip', 'bigchip/korea_bigchip_map.html'],
  ['semi', 'semiconductor/korea_semiconductor_map.html'],
  ['bio', 'bio/korea_bio_map.inline.js'],
  ['ship', 'ship/korea_ship_map.html'],
  ['defense', 'defense/korea_defense_map.html'],
  ['robot', 'robot/korea_robot_map.html'],
  ['auto', 'auto/korea_auto_map.html'],
  ['medtech', 'medtech/korea_medtech_map.html'],
  ['kconsume', 'kconsume/korea_kconsume_map.html'],
  ['cosmetics', 'cosmetics/korea_cosmetics_map.html'],
  ['kcontent', 'kcontent/korea_kcontent_map.html'],
  ['battery', 'battery/korea_battery_map.html'],
  ['renewable', 'renewable/korea_renewable_map.html'],
  ['nuclear', 'nuclear/korea_nuclear_map.html'],
  ['powergrid', 'powergrid/korea_powergrid_map.html'],
  ['finance', 'finance/korea_finance_map.html'],
  ['construction', 'construction/korea_construction_map.html'],
  ['software', 'software/korea_software_map.html'],
  ['holdings', 'holdings/korea_holdings_map.html'],
  ['telecom', 'telecom/korea_telecom_map.html'],
  ['chemical', 'chemical/korea_chemical_map.html'],
  ['travel', 'travel/korea_travel_map.html'],
  ['elec', 'elec/korea_elec_map.html'],
  ['metal', 'metal/korea_metal_map.html'],
];
