/**
 * Sector network profiles — layout, model, default filters, UI copy.
 * Keys match data-sector / sectorId in network JSON (semi → semiconductor in JSON).
 */

export const NETWORK_PROFILES = {
  semiconductor: {
    sectorId: 'semiconductor',
    dataSector: 'semi',
    model: 'supply_chain',
    layout: 'layeredSupplyChain',
    networkPath: 'data/networks/semiconductor.json',
    defaultEdgeTypes: ['supplies_to', 'equipment_for', 'material_for', 'customer_of', 'member_of'],
    defaultDepth: 1,
    defaultViewFilters: { hidePeer: true, hideInferred: false, hideReference: false, transactionalOnly: false },
    modelDescKo: '소재·장비에서 제조·패키징·고객으로 이어지는 공급망',
    modelDescEn: 'Supply chain from materials & equipment through manufacturing to customers',
    layers: [
      '소재',
      '전공정 장비',
      '후공정 장비',
      '부품/기판',
      '파운드리',
      'IDM/종합반도체',
      '팹리스',
      '디자인하우스',
      '패키징/테스트',
      '반도체 유통',
    ],
  },
  bigchip: {
    sectorId: 'bigchip',
    dataSector: 'bigchip',
    model: 'dual_anchor_comparison',
    layout: 'dualAnchor',
    networkPath: 'data/networks/bigchip.json',
    defaultEdgeTypes: [
      'produces', 'exposed_to', 'used_in_market', 'supplies_to', 'equipment_for',
      'material_for', 'packages_or_tests_for', 'technology_partnership', 'owns',
      'customer_of', 'peer', 'competes_with',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
    },
    modelDescKo: '삼성전자·SK하이닉스 양 앵커의 제품·공급·수요 생태계 비교',
    modelDescEn: 'Dual-anchor comparison of Samsung and SK hynix ecosystems',
    anchors: ['005930', '000660'],
  },
  holdings: {
    sectorId: 'holdings',
    dataSector: 'holdings',
    model: 'ownership_structure',
    layout: 'ownershipTree',
    networkPath: 'data/networks/holdings.json',
    defaultEdgeTypes: ['controls', 'owns', 'subsidiary_of', 'equity_stake'],
    defaultDepth: 2,
    defaultViewFilters: { hidePeer: true, hideInferred: false, hideReference: false, transactionalOnly: false },
    modelDescKo: '금융·지주 그룹의 지배·지분 구조',
    modelDescEn: 'Ownership and control structure of holding groups',
  },
  finance: {
    sectorId: 'finance',
    dataSector: 'finance',
    model: 'financial_group_ecosystem',
    layout: 'ownershipTree',
    networkPath: 'data/networks/finance.json',
    defaultEdgeTypes: [
      'owns', 'group_member', 'member_of', 'operates_in',
      'equity_investment', 'strategic_partnership', 'peer',
    ],
    defaultDepth: 2,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
    },
    modelDescKo: '금융지주·기업집단·독립 금융사의 소유·소속 구조입니다. 기업집단 소속은 직접 지분관계와 구분됩니다. 고객 관계는 포함하지 않습니다.',
    modelDescEn: 'Ownership and membership structure of financial holdings, corporate groups, and independent financial firms. Group membership is not direct ownership. Customer relationships are excluded.',
    layers: ['은행·금융지주', '증권·자산운용', '보험', '카드·캐피탈', '기타금융'],
    lanes: ['holding', 'bank', 'securities', 'insurance', 'card_capital', 'group', 'independent', 'peer'],
    roleAliases: {
      financial_holding: '은행·금융지주',
      bank: '은행·금융지주',
      securities: '증권·자산운용',
      asset_manager: '증권·자산운용',
      life_insurance: '보험',
      nonlife_insurance: '보험',
      insurance: '보험',
      card: '카드·캐피탈',
      capital: '카드·캐피탈',
      fintech: '기타금융',
      independent: '기타금융',
    },
  },
  defense: {
    sectorId: 'defense',
    dataSector: 'defense',
    model: 'program_ecosystem',
    layout: 'projectEcosystem',
    networkPath: 'data/networks/defense.json',
    defaultEdgeTypes: ['prime_contractor', 'subsystem_supplier', 'component_supplier', 'export_contract'],
    defaultDepth: 1,
    defaultViewFilters: { hidePeer: true, hideInferred: true, hideReference: true, transactionalOnly: true },
    modelDescKo: '무기체계·프로그램별 prime–supplier 네트워크',
    modelDescEn: 'Prime–supplier network by weapon program',
  },
  ship: {
    sectorId: 'ship',
    dataSector: 'ship',
    model: 'shipbuilding_project_ecosystem',
    layout: 'projectEcosystem',
    networkPath: 'data/networks/ship.json',
    defaultEdgeTypes: [
      'ordered', 'awarded_to', 'built_by', 'builds_vessel_type', 'exposed_to',
      'supplies_engine_to', 'supplies_steel_to', 'supplies_equipment_to',
      'owns', 'maintains', 'member_of', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
      showCompleted: false,
    },
    modelDescKo: '선주·수주계약·조선소·엔진·철강·기자재·선급·인도/MRO로 이어지는 프로젝트 중심 조선 생태계입니다. 선종·제품 연결은 개별 수주 계약과 구분됩니다.',
    modelDescEn: 'Project-centered shipbuilding ecosystem from owners and order contracts through yards, engines, steel, equipment, class, and delivery/MRO. Vessel-type links are not individual contracts.',
    // Existing map chain labels (cp_list) — do not invent alternate Korean names
    layers: ['종합조선', '엔진', '선체·보냉·구조재', '의장/배관', '서비스·해양플랜트', '해운물류'],
    lanes: [
      'shipowner',
      'order_contract',
      'shipyard',
      'engine_propulsion',
      'steel_material',
      'equipment',
      'electrical_automation',
      'classification',
      'delivery_mro',
    ],
    roleAliases: {
      shipyard: '종합조선',
      engine: '엔진',
      steel: '선체·보냉·구조재',
      ship_equipment: '의장/배관',
      offshore: '서비스·해양플랜트',
      shipping: '해운물류',
      electrical_automation: '의장/배관',
      defense_marine: '종합조선',
      mro: '서비스·해양플랜트',
      shipowner: '해운물류',
      order_contract: 'order_contract',
    },
  },
  bio: {
    sectorId: 'bio',
    dataSector: 'bio',
    model: 'pipeline_licensing',
    layout: 'assetLicensing',
    networkPath: 'data/networks/bio.json',
    defaultEdgeTypes: ['licensed_out_to', 'licensed_in_from', 'co_develops', 'manufactures_for', 'owns_pipeline'],
    defaultDepth: 1,
    defaultViewFilters: { hidePeer: true, hideInferred: true, hideReference: true, transactionalOnly: true },
    modelDescKo: '파이프라인의 보유·기술이전·공동개발 관계',
    modelDescEn: 'Pipeline ownership, licensing & co-development',
  },
  battery: {
    sectorId: 'battery',
    dataSector: 'battery',
    model: 'battery_circular_value_chain',
    layout: 'layeredSupplyChain',
    networkPath: 'data/networks/battery.json',
    defaultEdgeTypes: [
      'produces', 'exposed_to', 'supplies_material_to', 'supplies_cells_to',
      'supplies_component_to', 'supplies_equipment_to', 'owns', 'participates_in',
      'recycling_partnership', 'member_of', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
    },
    modelDescKo: '배터리 소재·장비·셀·수요시장·재활용으로 이어지는 순환형 밸류체인입니다. 제품·시장 연결은 기업 간 실제 거래와 구분됩니다.',
    modelDescEn: 'Circular battery value chain from materials and equipment through cells to demand markets and recycling. Product/market links are not company trade edges.',
    // Existing map chain labels (cp_list) — do not invent alternate names
    layers: ['소재', '부품', '장비', '셀', 'ESS', '수요시장', '재활용'],
    stageAliases: {
      raw_material: '소재',
      refining: '소재',
      cathode: '소재',
      anode: '소재',
      separator: '부품',
      electrolyte: '소재',
      copper_foil: '부품',
      equipment: '장비',
      cell: '셀',
      module_pack: 'ESS',
      ess: 'ESS',
      automotive: '수요시장',
      recycling: '재활용',
    },
  },
  elec: {
    sectorId: 'elec',
    dataSector: 'elec',
    model: 'electronics_component_value_chain',
    layout: 'electronicsValueChainEcosystem',
    networkPath: '../data/networks/elec.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'manufactures', 'produces', 'exposed_to',
      'used_in_device', 'used_in_technology', 'cross_sector_reference',
      'supplies_component_to', 'supplies_module_to', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: [
      'home_appliance',
      'display',
      'camera_module',
      'electronic_component',
      'end_market',
    ],
    modelDescKo: '가전·디스플레이·카메라모듈·전자부품 가치사슬. peer 문자열과 구조 분류를 실제 공급·지분과 분리합니다.',
    modelDescEn: 'Value chain for appliances, display, camera modules and electronic components. Separates peer labels and structural classification from verified supply and ownership.',
  },
  renewable: {
    sectorId: 'renewable',
    dataSector: 'renewable',
    model: 'renewable_project_value_chain',
    layout: 'renewableProjectEcosystem',
    networkPath: 'data/networks/renewable.json',
    defaultEdgeTypes: [
      'member_of', 'develops', 'manufactures', 'used_in_technology', 'supports_project_stage',
      'project_owner', 'project_developer', 'owns_stake_in', 'epc_for', 'operates', 'maintains',
      'supplies_module_to', 'supplies_structure_to', 'supplies_hydrogen_equipment_to',
      'power_purchase_agreement', 'memorandum_with', 'consortium_member', 'peer', 'reference',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
      showHistorical: false,
    },
    modelDescKo: '개발·인허가·금융·SPV·EPC·기자재·계통·PPA·운영으로 이어지는 재생에너지 프로젝트 가치사슬. MOU·개발·건설·운영을 구분합니다.',
    modelDescEn: 'Renewable project value chain from development and permitting through SPV, EPC, equipment, grid, PPA and O&M. Separates MOU, development, construction, and operations.',
    lanes: [
      'solar',
      'onshore_wind',
      'offshore_wind',
      'fuel_cell',
      'hydrogen',
      'renewable_operator',
    ],
    scopes: ['solar', 'onshore_wind', 'offshore_wind', 'fuel_cell', 'hydrogen', 'renewable_operator'],
  },
  nuclear: {
    sectorId: 'nuclear',
    dataSector: 'nuclear',
    model: 'nuclear_project_lifecycle_ecosystem',
    layout: 'nuclearProjectEcosystem',
    networkPath: 'data/networks/nuclear.json',
    defaultEdgeTypes: [
      'member_of', 'manufactures', 'supports_lifecycle_stage', 'exposed_to',
      'architect_engineer_for', 'epc_for', 'supplies_nsss_to', 'supplies_equipment_to',
      'maintains', 'operates', 'memorandum_with', 'preferred_bidder_for', 'selected_for',
      'consortium_member', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
      showHistorical: false,
    },
    modelDescKo: '발주·운영·설계·EPC·주기기·정비·SMR로 이어지는 원전 프로젝트 생애주기. MOU·선정·본계약·운영을 구분합니다.',
    modelDescEn: 'Nuclear project lifecycle from owner/operator through design, EPC, NSSS, O&M and SMR. Separates MOU, selection, contracts, and operations.',
    lanes: [
      'owner_operator',
      'export_epc_design',
      'nsss_reactor',
      'turbine_balance',
      'construction_ic',
      'fuel_maintenance',
      'smr_development',
      'overseas_project',
    ],
    scopes: ['large_nuclear', 'smr', 'domestic', 'overseas', 'om'],
  },
  powergrid: {
    sectorId: 'powergrid',
    dataSector: 'powergrid',
    model: 'grid_infrastructure_ecosystem',
    layout: 'gridInfrastructureEcosystem',
    networkPath: 'data/networks/powergrid.json',
    defaultEdgeTypes: [
      'member_of', 'manufactures', 'used_in_grid_stage', 'exposed_to',
      'supplies_transformer_to', 'supplies_cable_to', 'supplies_switchgear_to',
      'supplies_equipment_to', 'awarded_contract', 'project_supplier', 'epc_for',
      'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: {
      hidePeer: true,
      hideInferred: true,
      hideReference: false,
      transactionalOnly: false,
      showEnded: false,
    },
    modelDescKo: '발전→송전→변전→배전→수요로 이어지는 전력망 인프라 생태계. 설비·단계 구조와 확인된 수주·공급을 구분합니다.',
    modelDescEn: 'Grid infrastructure ecosystem from generation through T&D to demand. Separates equipment/stage structure from verified awards and supply.',
    lanes: [
      'generation_utility',
      'transmission_hvdc',
      'substation_protection',
      'distribution_power_electronics',
      'demand_overseas',
      'epc_services',
    ],
    stages: ['generation', 'transmission', 'substation', 'distribution', 'end_use'],
  },
  auto: {
    sectorId: 'auto',
    dataSector: 'auto',
    model: 'automotive_value_chain_ecosystem',
    layout: 'automotiveValueChainEcosystem',
    networkPath: '../data/networks/auto.json',
    defaultEdgeTypes: [
      'member_of', 'group_member', 'specializes_in', 'manufactures', 'produces',
      'exposed_to', 'used_in_technology', 'owns_stake_in',
      'supplies_component_to', 'supplies_system_to', 'supplies_tire_to',
      'supplies_lighting_to', 'supplies_electronics_to', 'used_in_vehicle',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: [
      'vehicle_oem',
      'powertrain',
      'electrification',
      'thermal_management',
      'chassis_braking_steering',
      'body_exterior',
      'interior',
      'lighting',
      'electronics_adas',
      'tire',
      'materials',
      'aftermarket',
      'end_market',
    ],
    modelDescKo: '완성차·파워트레인·전장·열관리·샤시·차체·타이어 등 자동차 가치사슬. 그룹 소속과 실제 공급·지분을 분리한다.',
    modelDescEn: 'Automotive value chain from OEMs through powertrain, electronics, thermal, chassis, body and tires. Separates group membership from actual supply and ownership.',
  },
  metal: {
    sectorId: 'metal',
    dataSector: 'metal',
    model: 'metals_material_value_chain',
    layout: 'metalsValueChainEcosystem',
    networkPath: '../data/networks/metal.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'produces', 'exposed_to_commodity', 'used_in_end_market',
      'cross_sector_reference', 'supplies_material_to', 'supplies_metal_product_to',
      'offtake_agreement_with', 'owns_stake_in', 'owns_facility', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: [
      'raw_material',
      'smelting_refining',
      'steelmaking',
      'nonferrous_metal',
      'rolling_processing',
      'specialty_alloy',
      'metal_products',
      'recycling',
      'distribution_trading',
      'end_market',
    ],
    modelDescKo: '철강·비철·트레이딩·금속제품 가치사슬. 원자재 노출·구조 분류와 실제 공급·지분·시설을 분리합니다.',
    modelDescEn: 'Value chain for steel, nonferrous metals, trading and metal products. Separates commodity exposure and structural classification from verified supply, ownership and facilities.',
  },
  construction: {
    sectorId: 'construction',
    dataSector: 'construction',
    model: 'construction_development_project_ecosystem',
    layout: 'constructionProjectEcosystem',
    networkPath: '../data/networks/construction.json',
    defaultEdgeTypes: [
      'main_contractor', 'epc_for', 'project_owner', 'project_developer',
      'owns_stake_in', 'pfv_shareholder', 'constructs', 'consortium_member',
      'specializes_in', 'manufactures', 'operates_brand',
    ],
    defaultDepth: 1,
    lanes: ['developer_housing', 'general_contractor', 'plant_infra', 'overseas_epc', 'machinery', 'finance_trust'],
    modelDescKo: '토지·시행·SPC/PFV·금융·설계·시공·분양·준공 및 해외 EPC 생애주기. 총사업비·도급·기업지분·PF를 분리한다.',
    modelDescEn: 'Land, developer, SPC/PFV, finance, design, contracting, presale, completion and overseas EPC. Separates total project cost, contract value, company share and PF.',
  },
  software: {
    sectorId: 'software',
    dataSector: 'software',
    model: 'software_product_platform_ecosystem',
    layout: 'softwarePlatformEcosystem',
    networkPath: '../data/networks/software.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'operates_platform', 'offers_cloud_service',
      'used_in_industry', 'cross_sector_reference', 'supplies_software_to',
      'partners_with', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: [
      'data_ai', 'managed_service', 'cloud_infrastructure', 'cybersecurity',
      'enterprise_software', 'commerce_platform', 'industrial_software',
    ],
    modelDescKo: '소프트웨어 제품·플랫폼·클라우드·산업 적용 생태계. 기술 연동·산업 노출과 실제 공급·파트너십을 분리합니다.',
    modelDescEn: 'Software product, platform, cloud and industry ecosystem. Separates integration/industry exposure from verified supply and partnerships.',
  },
  telecom: {
    sectorId: 'telecom',
    dataSector: 'telecom',
    model: 'telecommunications_network_service_ecosystem',
    layout: 'telecomNetworkServiceEcosystem',
    networkPath: '../data/networks/telecom.json',
    defaultEdgeTypes: [
      'member_of', 'offers_service', 'manufactures_equipment', 'produces_component',
      'supports_network_generation', 'cross_sector_reference', 'supplies_equipment_to',
      'deploys_network_for', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: ['network_operator', 'network_equipment', 'optical_wireless_component'],
    modelDescKo: '통신사·망·장비·광부품 생태계. 주파수 할당·호환 인증과 실제 공급·구축 계약을 분리합니다.',
    modelDescEn: 'Carrier, network, equipment and optical-component ecosystem. Separates spectrum/certification from verified supply and deployment contracts.',
  },
  kconsume: {
    sectorId: 'kconsume',
    dataSector: 'kconsume',
    model: 'consumer_brand_distribution_ecosystem',
    layout: 'consumerBrandDistributionEcosystem',
    networkPath: '../data/networks/kconsume.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'operates_brand', 'owns_brand', 'licenses_brand',
      'sold_through_channel', 'operates_retail_channel', 'exposed_to_market',
      'cross_sector_reference', 'manufactures_for', 'distributes_for', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: ['brand_owner', 'manufacturing', 'retail_channel', 'leisure_lifestyle'],
    modelDescKo: '소비재 브랜드·제조·유통·레저 가치사슬. 브랜드·채널 구조 분류와 실제 제조·유통·지분 계약을 분리합니다.',
    modelDescEn: 'Consumer brand, manufacturing, retail and leisure value chain. Separates brand/channel structural classification from verified manufacturing, distribution and ownership contracts.',
  },
  cosmetics: {
    sectorId: 'cosmetics',
    dataSector: 'cosmetics',
    model: 'beauty_brand_manufacturing_distribution_ecosystem',
    layout: 'beautyValueChainEcosystem',
    networkPath: '../data/networks/cosmetics.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'owns_brand', 'operates_brand', 'licenses_brand',
      'provides_odm', 'provides_oem', 'used_in_product_category', 'exposed_to_market',
      'sold_through_channel', 'cross_sector_reference', 'manufactures_for',
      'distributes_for', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: ['brand_owner', 'odm_oem', 'beauty_device', 'distributor'],
    modelDescKo: '브랜드·ODM/OEM·미용기기·유통 가치사슬. 브랜드·시장 노출·구조 분류와 실제 ODM·유통·지분 계약을 분리합니다.',
    modelDescEn: 'Value chain for brands, ODM/OEM, aesthetic devices and distribution. Separates brand/market structural classification from verified ODM, distribution and ownership contracts.',
  },
  kcontent: {
    sectorId: 'kcontent',
    dataSector: 'kcontent',
    model: 'content_ip_production_distribution_ecosystem',
    layout: 'contentIpDistributionEcosystem',
    networkPath: '../data/networks/kcontent.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'represents_artist', 'manages_artist',
      'owns_ip', 'controls_ip', 'produces_content', 'cross_sector_reference',
      'distributes_to', 'streams_on', 'co_produces_with', 'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: ['label_agency', 'production_studio', 'ip_rights', 'distributor', 'platform'],
    modelDescKo: '콘텐츠 IP·레이블·제작·배급·플랫폼 생태계. 아티스트 소속·IP 포트폴리오 구조와 실제 전속·배급·독점 계약을 분리합니다.',
    modelDescEn: 'Content IP, label, production, distribution and platform ecosystem. Separates artist affiliation and IP portfolio structure from verified exclusive, distribution and ownership contracts.',
  },
  medtech: {
    sectorId: 'medtech',
    dataSector: 'medtech',
    model: 'medical_device_product_regulatory_ecosystem',
    layout: 'medicalDeviceEcosystem',
    networkPath: '../data/networks/medtech.json',
    defaultEdgeTypes: [
      'member_of', 'specializes_in', 'used_in_specialty', 'cross_sector_reference',
      'approved_or_cleared_by', 'registered_in_market', 'exposed_to_market',
      'supplies_device_to', 'distributes_for', 'installed_at_provider',
      'owns_stake_in', 'peer',
    ],
    defaultDepth: 1,
    defaultViewFilters: { transactionalOnly: false, hidePeer: true, hideInferred: true },
    lanes: [
      'in_vitro_diagnostics',
      'digital_health_samd',
      'patient_monitoring',
      'surgical_device',
      'dental_device',
    ],
    modelDescKo: '의료기기 제품군·진료영역·인허가·유통 생태계. 규제 상태와 실제 공급·설치·유통 계약을 분리합니다.',
    modelDescEn: 'Medical device product, specialty, regulatory and distribution ecosystem. Separates clearance status from verified supply, installation and distribution contracts.',
  },
  robot: {
    sectorId: 'robot',
    dataSector: 'robot',
    model: 'robotics_component_system_application_ecosystem',
    layout: 'roboticsValueChainEcosystem',
    networkPath: '../data/networks/robot.json',
    defaultEdgeTypes: [
      'member_of', 'produces_component', 'produces_robot', 'member_of_category',
      'supports_application', 'cross_sector_reference', 'supplies_component_to',
      'supplies_robot_to', 'deployed_at', 'invests_in', 'peer',
    ],
    defaultDepth: 1,
    lanes: [
      'precision_component',
      'actuator_drive',
      'robot_software',
      'industrial_robot',
      'collaborative_robot',
      'logistics_robot',
      'system_integration',
      'end_market',
    ],
    modelDescKo: '로봇 부품·제품·유형·SI·적용산업 생태계. 구조 분류와 실제 공급·도입·투자를 분리합니다.',
    modelDescEn: 'Robotics component, product, category, SI and end-market ecosystem. Separates structure from verified supply, deployment and investment.',
  },
};

/** Pilot sectors with structured network JSON (Phase 2 + 3A + 3B) */
export const PILOT_NETWORK_SECTORS = new Set(['semiconductor', 'holdings', 'defense', 'bio', 'bigchip', 'battery', 'ship', 'finance', 'powergrid', 'nuclear', 'renewable', 'construction', 'auto', 'elec', 'metal', 'cosmetics', 'kconsume', 'kcontent', 'medtech', 'software', 'telecom', 'robot']);

export function profileForDataSector(dataSector) {
  if (dataSector === 'semi') return NETWORK_PROFILES.semiconductor;
  return Object.values(NETWORK_PROFILES).find((p) => p.dataSector === dataSector) || null;
}
