/**
 * Structured relation-network schema (source of truth for validation & migration).
 * Browser runtime mirrors these enums in js/relation_network.js.
 */

/** @typedef {'listed_company'|'global_company'|'program'|'project'|'pipeline'|'group'|'institution'} NetworkNodeType */

/** @typedef {'confirmed'|'inferred'|'reference'} EdgeStatus */

/** @typedef {'high'|'medium'|'low'} EdgeConfidence */

/**
 * Sector-specific allowed edge types.
 * peer is always undirected; transactional types require direction.
 */
export const SECTOR_EDGE_TYPES = {
  semiconductor: [
    'supplies_to',
    'equipment_for',
    'material_for',
    'manufactures_for',
    'packages_or_tests_for',
    'licenses_ip_to',
    'customer_of',
    'technology_partnership',
    'member_of',
    'peer',
  ],
  bigchip: [
    'produces',
    'develops',
    'manufactures',
    'exposed_to',
    'used_in_market',
    'supplies_to',
    'equipment_for',
    'material_for',
    'packages_or_tests_for',
    'licenses_to',
    'joint_development',
    'technology_partnership',
    'owns',
    'subsidiary_of',
    'joint_venture',
    'customer_of',
    'peer',
    'competes_with',
    'reference',
    'member_of',
  ],
  battery: [
    'member_of',
    'produces',
    'manufactures',
    'develops',
    'used_in_process',
    'exposed_to',
    'supplies_material_to',
    'supplies_equipment_to',
    'supplies_cells_to',
    'supplies_component_to',
    'owns',
    'subsidiary_of',
    'joint_venture',
    'offtake_agreement',
    'long_term_supply',
    'technology_license',
    'joint_development',
    'strategic_investment',
    'recycling_partnership',
    'participates_in',
    'operates',
    'supplies_to_project',
    'peer',
    'reference',
    'inferred',
  ],
  elec: [
    'component_supplier',
    'module_supplier',
    'display_supplier',
    'manufacturing_partner',
    'customer',
    'peer',
  ],
  renewable: [
    'member_of',
    'develops',
    'manufactures',
    'used_in_technology',
    'supports_project_stage',
    'exposed_to',
    'project_owner',
    'project_developer',
    'owns_stake_in',
    'spv_shareholder',
    'project_operator',
    'development_rights',
    'epc_for',
    'engineering_for',
    'constructs',
    'commissions',
    'operates',
    'maintains',
    'grid_connects',
    'participates_in',
    'supplies_module_to',
    'supplies_inverter_to',
    'supplies_turbine_to',
    'supplies_structure_to',
    'supplies_cable_to',
    'supplies_substation_to',
    'supplies_fuel_cell_to',
    'supplies_hydrogen_equipment_to',
    'supplies_storage_to',
    'supplies_equipment',
    'power_purchase_agreement',
    'rec_purchase_agreement',
    'hydrogen_offtake',
    'power_purchase',
    'finances',
    'insures',
    'consortium_member',
    'joint_development',
    'memorandum_with',
    'technology_partnership',
    'joint_venture',
    'owns',
    'operates_or_maintains',
    'peer',
    'reference',
    'inferred',
    'ended',
  ],
  nuclear: [
    'member_of',
    'manufactures',
    'develops',
    'licensed_for',
    'used_in_reactor',
    'exposed_to',
    'supports_lifecycle_stage',
    'project_owner',
    'project_developer',
    'project_operator',
    'export_lead',
    'selected_for',
    'preferred_bidder_for',
    'negotiates_for',
    'epc_for',
    'architect_engineer_for',
    'designs_for',
    'builds',
    'commissions',
    'operates',
    'maintains',
    'decommissions',
    'supplies_nsss_to',
    'supplies_reactor_to',
    'supplies_turbine_to',
    'supplies_equipment_to',
    'supplies_ic_to',
    'supplies_fuel_to',
    'supplies_service_to',
    'consortium_member',
    'joint_development',
    'technology_license',
    'memorandum_with',
    'feasibility_study_for',
    'strategic_partnership',
    'owns',
    'equity_investment',
    'joint_venture',
    'peer',
    'reference',
    'inferred',
    'ended',
  ],
  powergrid: [
    'member_of',
    'manufactures',
    'develops',
    'used_in_grid_stage',
    'exposed_to',
    'supports_market',
    'supplies_transformer_to',
    'supplies_cable_to',
    'supplies_switchgear_to',
    'supplies_equipment_to',
    'awarded_contract',
    'project_supplier',
    'epc_for',
    'consortium_member',
    'technology_partnership',
    'owns',
    'joint_venture',
    'maintains',
    'project_owner',
    'project_operator',
    'participates_in',
    'located_in',
    'peer',
    'reference',
    'inferred',
    'ended',
  ],
  auto: [
    'member_of',
    'group_member',
    'specializes_in',
    'manufactures',
    'produces',
    'operates_brand',
    'used_in_technology',
    'used_in_vehicle_segment',
    'exposed_to',
    'located_in_stage',
    'supplies_component_to',
    'supplies_system_to',
    'supplies_material_to',
    'supplies_tire_to',
    'supplies_lighting_to',
    'supplies_electronics_to',
    'develops_with',
    'licenses_to',
    'participates_in',
    'owns',
    'owns_stake_in',
    'operates_joint_venture',
    'joint_venture',
    'awarded_contract',
    'nominated_supplier_for',
    'used_in_vehicle',
    'competes_with',
    'peer',
    'reference',
    'inferred',
    'ended',
  ],
  ship: [
    'member_of',
    'builds_vessel_type',
    'manufactures',
    'develops',
    'exposed_to',
    'used_in_vessel',
    'ordered',
    'awarded_to',
    'built_by',
    'project_owner',
    'project_operator',
    'consortium_member',
    'delivered_to',
    'scheduled_for_delivery',
    'supplies_engine_to',
    'supplies_steel_to',
    'supplies_equipment_to',
    'supplies_electrical_to',
    'supplies_automation_to',
    'supplies_material_to',
    'classifies',
    'maintains',
    'retrofits',
    'aftersales_for',
    'owns',
    'subsidiary_of',
    'joint_venture',
    'strategic_partnership',
    'peer',
    'reference',
    'inferred',
  ],
  defense: [
    'prime_contractor',
    'subsystem_supplier',
    'component_supplier',
    'engine_supplier',
    'export_contract',
    'licensed_production',
    'joint_development',
    'manufactures',
    'develops',
    'end_user',
    'peer',
  ],
  metal: [
    'supplies_material',
    'processes',
    'distributes',
    'equipment_supplier',
    'end_market_exposure',
    'customer',
    'peer',
  ],
  construction: [
    'member_of',
    'operates_brand',
    'specializes_in',
    'builds',
    'manufactures',
    'exposed_to',
    'owns_stake_in',
    'project_owner',
    'project_developer',
    'spc_shareholder',
    'pfv_shareholder',
    'reit_shareholder',
    'owns',
    'subsidiary_of',
    'architect_for',
    'engineering_for',
    'main_contractor',
    'epc_for',
    'constructs',
    'consortium_member',
    'subcontractor_for',
    'commissioning_for',
    'finances',
    'arranges_pf',
    'guarantees',
    'operates',
    'property_manages',
    'maintains',
    'supplies_equipment_to',
    'supplies_machinery_to',
    'supplies_material_to',
    'awarded_contract',
    'preferred_bidder_for',
    'memorandum_with',
    'peer',
    'reference',
    'inferred',
    'ended',
  ],
  finance: [
    'owns',
    'controls',
    'equity_investment',
    'subsidiary_of',
    'group_member',
    'affiliated_with',
    'joint_venture',
    'strategic_investment',
    'strategic_partnership',
    'distribution_partnership',
    'platform_partnership',
    'bancassurance_partnership',
    'technology_partnership',
    'member_of',
    'operates_in',
    'peer',
    'reference',
    'inferred',
  ],
  holdings: [
    'owns',
    'controls',
    'subsidiary_of',
    'group_member',
    'second_tier_subsidiary',
    'equity_stake',
    'peer',
  ],
  software: [
    'cloud_partner',
    'technology_integration',
    'reseller',
    'service_provider',
    'platform_dependency',
    'strategic_investment',
    'enterprise_contract',
    'peer',
  ],
  telecom: [
    'equipment_supplier',
    'network_operator',
    'infrastructure_partner',
    'roaming_or_interconnect',
    'cloud_partner',
    'content_distribution',
    'satellite_service',
    'peer',
  ],
  kconsume: [
    'manufactures_for',
    'brand_owner',
    'distributes',
    'sells_through',
    'franchise_operator',
    'logistics_partner',
    'regional_expansion',
    'peer',
  ],
  cosmetics: [
    'odm_for',
    'oem_for',
    'supplies_ingredient',
    'supplies_packaging',
    'distributes',
    'brand_owner',
    'device_distribution',
    'peer',
  ],
  kcontent: [
    'owns_ip',
    'produces',
    'publishes',
    'distributes',
    'streams_on',
    'management_contract',
    'adaptation',
    'co_production',
    'subsidiary_of',
    'strategic_investment',
    'peer',
  ],
  bio: [
    'owns_pipeline',
    'licensed_out_to',
    'licensed_in_from',
    'co_develops',
    'manufactures_for',
    'clinical_collaboration',
    'commercialization_rights',
    'equity_investment',
    'peer',
  ],
  medtech: [
    'manufactures',
    'distributes',
    'approved_in',
    'used_for',
    'supplies_to',
    'co_development',
    'strategic_partnership',
    'peer',
  ],
  robot: [
    'component_supplier',
    'software_provider',
    'system_integrator',
    'deployed_at',
    'distributes',
    'joint_development',
    'strategic_investment',
    'peer',
  ],
};

/** Undirected edge types — no arrowheads */
export const UNDIRECTED_EDGE_TYPES = new Set(['peer', 'consortium_member', 'joint_development', 'competes_with']);

/** Legacy partner kind → schema edge type (fallback adapter) */
export const LEGACY_KIND_MAP = {
  supplier: 'supplies_to',
  customer: 'customer_of',
  peer: 'peer',
  member: 'member_of',
  backing: 'equity_investment',
  theme: 'end_market_exposure',
  export: 'export_contract',
};

/**
 * @param {object} network
 * @returns {string} sectorId key used in profiles
 */
export function resolveSectorKey(network) {
  const id = network?.sectorId || '';
  const aliases = {
    semi: 'semiconductor',
    ship: 'ship',
    medtech: 'medtech',
    kconsume: 'kconsume',
    kcontent: 'kcontent',
    software: 'software',
    robot: 'robot',
  };
  return aliases[id] || id;
}

export function allowedEdgeTypes(sectorId) {
  return SECTOR_EDGE_TYPES[resolveSectorKey({ sectorId })] || ['peer'];
}

/** Statuses that imply transactional (strong line) edges */
export const TRANSACTIONAL_STATUSES = new Set(['confirmed', 'reported']);

/** Statuses excluded from default pilot views */
export const DEFAULT_HIDDEN_STATUSES = {
  bio: new Set(['peer', 'reference', 'inferred']),
  defense: new Set(['peer', 'reference', 'inferred']),
  semiconductor: new Set(['peer']),
  holdings: new Set(['peer']),
};

export function isTransactionalStatus(status) {
  return TRANSACTIONAL_STATUSES.has(status);
}

export function isUndirectedEdgeType(type) {
  return UNDIRECTED_EDGE_TYPES.has(type);
}

/** Confirmed edges must pass human review with direct evidence metadata */
export function meetsConfirmedRequirements(edge) {
  if (edge.status !== 'confirmed') return { ok: true };
  const issues = [];
  if (!edge.lastVerifiedAt) issues.push('missing_lastVerifiedAt');
  if (edge.reviewStatus !== 'reviewed') issues.push('reviewStatus_not_reviewed');
  if (!edge.reviewedAt) issues.push('missing_reviewedAt');
  if (!edge.reviewedBy) issues.push('missing_reviewedBy');
  const evs = Array.isArray(edge.evidence) ? edge.evidence : [];
  if (!evs.length) issues.push('missing_evidence');
  for (const ev of evs) {
    if (ev.directEvidence !== true) issues.push('directEvidence_not_true');
    if (ev.reviewStatus !== 'reviewed') issues.push('evidence_not_reviewed');
    if (!ev.url || !ev.title) issues.push('evidence_incomplete');
    if (!ev.publishedAt && !ev.accessedAt) issues.push('evidence_missing_date');
  }
  return { ok: issues.length === 0, issues };
}
